baseUrl=https://the-internet.herokuapp.com
jsalert=https://the-internet.herokuapp.com/javascript_alerts
browserName=chrome
iFrameUrl=https://the-internet.herokuapp.com/iframe
uploadUrl=https://the-internet.herokuapp.com/upload
fileUrl=src\test\resources\sample.txt
windowsUrl=https://the-internet.herokuapp.com/windows